---
- hosts: "tag_Name_web*"
  become: true
  vars_files:
    - /etc/ansible/roles/geerlingguy.apache/vars/main.yml
    - /etc/ansible/roles/geerlingguy.apache/vars/certificates.yml
  roles:
    - { role: geerlingguy.apache }
    - { role: example.com-web }
